### ISSUE TITLE
Справочник «Организации»

### ISSUE THREAD

**Issue by metz-hei** [metz-hei/psb#103]

**Comment by metz-hei** [comment]
![Image](https://github.com/user-attachments/assets/c6a34e82-bbfd-471b-b855-d47381a0953e)

**Comment by metz-hei** [comment]
Отправили исследователям 11 ноября

**Comment by Mary-Korshunova** [comment]
Руслан: ок

Гугл док:
https://docs.google.com/document/d/1SR6baY5nA6qaWpSTZBtJmlGGZcLB2kfDrAGaIpN2DZI/edit?tab=t.0
