### ISSUE TITLE
Шаринг

### ISSUE THREAD

**Issue by metz-hei** [metz-hei/psb#116]
В дизайнах мы много фантазируем на предмет шаринга. Часто рисуем какие-то системные экраны, но на самом деле у нас в андройде есть модуль ShareHelper который работает и выглядит совершенно иначе.
Надо разобраться почему мы используем самописный модуль вместо системного. Можем ли мы от него отказаться? Какие могут быть последствия?

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/dccd18a6-dbb4-4eee-9acf-11ce05a0663a">

**Comment by wayneris** [comment]
Отдала на ревью Жене Баринову
