### ISSUE TITLE
Незалипающий флоатинг экшн бар

### ISSUE THREAD

**Issue by metz-hei** [metz-hei/psb#125]
Юля Белова пришла с доработкой. Ранее планировалось, что у дизайнера будет выбор между залипающим и незалипающим флоатинг экшн баром (и просто кнопокой??).

Выбор ручной, по критерию высоты экрана, если высокий то флоатинг прилипает снизу, если низкий, то не прилипает. 

[Кейс №1](https://www.figma.com/design/kp7jM5s5u20EDh2nynhfgx/%D0%A0%D0%B5%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D1%81%D0%B0%D0%BA%D1%81%D0%B5%D0%B7-%D1%81%D0%BA%D1%80%D0%B8%D0%BD%D0%B0?node-id=4199-49849&t=2vOqrtpjADYcyAo1-1)

[Кейс №2](https://www.figma.com/design/JGj9IhZcrmROnBUgd9VhG4/14-%E2%9C%85-%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C-%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B9-%D1%82%D0%B8%D0%BF%D1%8B-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%F0%9F%A7%A1%D0%A0%D0%BE%D0%B7%D0%BD%D0%B8%D1%86%D0%B0?node-id=2813-36983&t=tfDem8cJTyRiAucj-1)

### Вопросы
1. Градиент у флоатинга?
2. Что значит есть скролл, типа если его не было, а потом он появился, кнопки будут ездить туда-сюда? Типа я развернул подробности операции, напр
3. Непонятно как будет выпадашка работать, она умеет вниз выпадать у флоатинга?
4. Сборка всегда будет через флоатинг? т е он должен уметь адаптироваться?

**Comment by wayneris** [comment]
Итог: 

**1. Компонент остаётся тем же.** 

**2. Со стороны паттернов:** 
Доработать паттерн Экран успеха - пропишем правила в паттерне, когда идут статичные кнопки (если мало контента - сколько? сам дизайнер определяет?) и если контент может раскрываться (тогда флоатинг, если есть скролл или какие-то раскрывающиеся элементы) 

Может в процентах указать? Если контент занимается меньше или больше 70%, так как сетка динамическая. Когда не знаем, на каком экране откроет пользователь.

**Comment by wayneris** [comment]
Дальше действуем в рамках [#145](https://github.com/metz-hei/psb/issues/145)
