### ISSUE TITLE
Обсудить с тех. лидами депрекейт самописного диалога на андроид

### ISSUE THREAD

**Issue by wayneris** [metz-hei/psb#138]
Необходимо обсудить с тех. лидами депрекейт самописного диалога на андроид. Существующему решению более 5 лет. В кит добавлял в августе 2016 Владимир Нечуговских.

В основе компонента, диалог - называется ChoiceDialog. Вызов данного диалога со сценарием "поделиться" производится через класс ShareHelper

**Comment by metz-hei** [comment]
перенес в джиру

**Comment by wayneris** [comment]
Обсудили. Можно депрекейтить. Задачу заведу
