### ISSUE TITLE
Как правильно использовать Тост

### ISSUE THREAD

**Issue by metz-hei** [metz-hei/psb#69]
Когда использовать тост: https://docs.google.com/document/d/15_5XhFGms1uZj2DdADVqO-kVxuekIp4bvI99NZgHnaY/edit?usp=sharing

**Comment by metz-hei** [comment]
Когда тост появляется снизу, то если есть кнопка баттон праймари, то он закрывает ее. Особенно на саццезах

**Comment by metz-hei** [comment]
От Аланы
https://www.figma.com/community/file/1257619367116825357/error-states-mobile-wireframe-flows
https://www.smashingmagazine.com/2016/09/how-to-design-error-states-for-mobile-apps/

**Comment by metz-hei** [comment]
![Image](https://github.com/user-attachments/assets/1bd0f8c8-cb12-4fe5-a595-734d301859c7)

**Comment by metz-hei** [comment]
Нотисы — это ТОЛЬКО уведомления ДБО к пользователю о каких-то процессах внутри функционала, о сервисах или продуктах банка. Например: 
Подтвердите email (До 15.04.23 подтвердите ваш email в разделе ДБО для авторизации в зону для развлечений) или Отчёт сформирован (За период с 5 сентября 2023 по 5 декабря 2023) или 12 дней до истечения полномочий (Доступ для Морозова Елена Валерьевна в “ПСБ Бизнес” моожет быть приостановлен. Продлите срок действия полномочий.). 

Уведомления бывают 4 типов: 
info
success (успешые)
warning (предупреждающие)
error (критичные) — например, "полномочия истекли". 

И поэтому уведомления ДБО никак не относятся к ошибкам, которые находятся внутри флоу или отказов работы системы, сервера (505 и так далее)

А тот паттерн, про который мы говорим — это ошибки внутри флоу, когда не сформировался документ, выписка или что-то такое, отсутсвие интернета, сети, сервер упал и так далее. Все вот эти 400+ ошибки

Это опять же насколько я это понимаю. Возможно, на бою оно не всегда так отрабатывает. Например, мобильщик недавно сказал, что ошибка с интернетом через нотис отображается, а это неправильно, увы((

**Comment by metz-hei** [comment]
Дальше в рамках [149](https://github.com/metz-hei/psb/issues/149)

**Comment by annabykovskaya** [comment]
> ![Image](https://github.com/user-attachments/assets/1bd0f8c8-cb12-4fe5-a595-734d301859c7)

@metz-hei, что это? откуда это?
