### ISSUE TITLE
Когда мы покидаем любую форму редактирования

### ISSUE THREAD

**Issue by metz-hei** [metz-hei/psb#88]
![Image](https://github.com/user-attachments/assets/68bf8ca4-6ee5-4482-a08d-2c5b7834a508)

![telegram-cloud-photo-size-2-5343535930587340297-y](https://github.com/user-attachments/assets/5b53a8e5-b79f-49c5-990e-fd0b5fbd3525)

**Comment by Mary-Korshunova** [comment]
Отправили на ревью Евгению Баринову
